language: node_js
env:
  - CXX="g++-4.8"
node_js:
  - "0.12"
  - "0.10"
  - "iojs-v1"
  - "iojs-v2"
  - "iojs-v3"
  - "4"
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-4.8
    - gcc-4.8
